

model_name=EMAformer

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/PEMS/ \
  --data_path PEMS04.npz \
  --model_id PEMS04_96_12 \
  --model $model_name \
  --data PEMS \
  --features M \
  --seq_len 96 \
  --pred_len 12 \
  --e_layers 1 \
  --enc_in 307 \
  --dec_in 307 \
  --c_out 307 \
  --des 'Exp' \
  --d_model 1024 \
  --d_ff 1024 \
  --n_heads 4 \
  --patience 5 \
  --train_epochs 30 \
  --lradj type3 \
  --output_proj_dropout 0 \
  --learning_rate 0.0005 \
  --itr 1 \
  --use_norm 0 \
  --cycle 288

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/PEMS/ \
  --data_path PEMS04.npz \
  --model_id PEMS04_96_24 \
  --model $model_name \
  --data PEMS \
  --features M \
  --seq_len 96 \
  --pred_len 24 \
  --e_layers 1 \
  --enc_in 307 \
  --dec_in 307 \
  --c_out 307 \
  --des 'Exp' \
  --d_model 1024 \
  --d_ff 1024 \
  --n_heads 4 \
  --patience 5 \
  --train_epochs 30 \
  --lradj type3 \
  --output_proj_dropout 0 \
  --learning_rate 0.0005 \
  --itr 1 \
  --use_norm 0 \
  --cycle 288

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/PEMS/ \
  --data_path PEMS04.npz \
  --model_id PEMS04_96_48 \
  --model $model_name \
  --data PEMS \
  --features M \
  --seq_len 96 \
  --pred_len 48 \
  --e_layers 1 \
  --enc_in 307 \
  --dec_in 307 \
  --c_out 307 \
  --des 'Exp' \
  --d_model 1024 \
  --d_ff 1024 \
  --n_heads 4 \
  --patience 5 \
  --train_epochs 30 \
  --lradj type3 \
  --output_proj_dropout 0 \
  --learning_rate 0.0005 \
  --itr 1 \
  --use_norm 0 \
  --cycle 288

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/PEMS/ \
  --data_path PEMS04.npz \
  --model_id PEMS04_96_96 \
  --model $model_name \
  --data PEMS \
  --features M \
  --seq_len 96 \
  --pred_len 96 \
  --e_layers 1 \
  --enc_in 307 \
  --dec_in 307 \
  --c_out 307 \
  --des 'Exp' \
  --d_model 1024 \
  --d_ff 1024 \
  --learning_rate 0.0005 \
  --itr 1 \
  --n_heads 4 \
  --patience 5 \
  --train_epochs 30 \
  --lradj type3 \
  --output_proj_dropout 0 \
  --use_norm 0 \
  --cycle 288
